In [439]:
import numpy as np

### Classical Orbital elements

In [440]:
# \mew_earth = G* Mass_earth 
mew_earth = 398600.4 # in km^3 s^-2

I_vec = [1, 0, 0]
J_vec = [0, 1, 0]
K_vec = [0, 0, 1]

r_vec = np.array([-6000, 4000, 0]) #in km
v_vec = np.array([2, 0, 7.5]) #in km/s

r = np.linalg.norm(r_vec)
v = np.linalg.norm(v_vec)
a = -mew_earth/2 /(v**2/2 - mew_earth/r)

print(f"r = {r} Km ; v = {v} Km/s ; a = {a} Km")

r = 7211.102550927979 Km ; v = 7.762087348130012 Km/s ; a = 7924.1682041538825 Km


In [441]:
# angular momentum, h in km^2/s
h_vec = np.cross(r_vec, v_vec)
h = np.linalg.norm(h_vec)
print(h_vec, h)

[30000. 45000. -8000.] 54671.74773134658


In [442]:
# eccentricity
e_vec = np.cross(v_vec, h_vec)/mew_earth - r_vec/r
e = np.linalg.norm(e_vec)
print(e_vec, e)

[-0.01466235  0.04991535  0.22579004] 0.23170599688792248


In [443]:
# ascending Node vector
temp = np.cross(K_vec, h_vec)

n_vec = temp/np.linalg.norm(temp)
n_vec

array([-0.83205029,  0.5547002 ,  0.        ])

In [444]:
# Omega, Right ascession of the ascending node
temp1 = np.dot(I_vec,n_vec)
temp2 = np.dot(J_vec, n_vec)

Omega1 = np.arccos(temp1)
Omega2 = np.arcsin(temp2)

print(temp1, temp2,"\n")
print(Omega1, np.degrees(Omega1))
print(Omega2, np.degrees(Omega2))

Omega = np.deg2rad(146.310) #select values suitably

-0.8320502943378437 0.5547001962252291 

2.5535900500422257 146.30993247402023
0.5880026035475676 33.69006752597979


In [445]:
# i, Orbital Inclination
temp1 = np.dot(K_vec, h_vec/h)
temp2 = np.linalg.norm(np.cross(K_vec, h_vec/h))

i1 = np.arccos(temp1)
i2 = np.arcsin(temp2)

print(temp1, temp2,"\n")
print(i1, np.degrees(i1))
print(i2, np.degrees(i2))

i = np.deg2rad(98.414) #select value suitably

-0.14632786278045254 0.9892361480324631 

1.717651477687257 98.41418034588911
1.4239411759025369 81.58581965411092


In [446]:
# omega, argument of periapsis
temp1 = np.dot(n_vec, e_vec/e)
temp2 = np.dot(h_vec/h, np.cross(n_vec, e_vec/e))

omega1 = np.arccos(temp1)
omega2 = np.arcsin(temp2)

print(temp1, temp2,"\n")
print(omega1, np.degrees(omega1))
print(omega2, np.degrees(omega2))

omega = np.deg2rad(80.087) #select value suitably

0.1721486378091282 0.9850709855134614 

1.3977858705056814 80.08723104299536
1.3977858705056827 80.08723104299544


In [447]:
# calculating delta_t = t-t0

# value of cos(Theta)

val1 = np.dot(r_vec/r, e_vec/e)
val1

0.1721486378091282

In [448]:
# value of sin(phi)

val2 = np.dot(v_vec/v, r_vec/r)
val2

-0.21438828423859346

In [449]:
########################
# set suitable theta

Theta = np.arccos(val1)
Theta = 360-np.degrees(Theta)
Theta

279.91276895700463

In [450]:
# Finding E

E = 2* np.arctan(np.sqrt((1-e)/(1+e)) * np.tan(Theta/2))
np.degrees(E)

-157.5448359593848

In [451]:
n = np.sqrt(mew_earth/a**3)

# delta_T in seconds
delta_T = (E-e*np.sin(E))/n

delta_T

-2973.273570292116

### Complete set of Orbital Variables

In [452]:
# Declination of celetial Latitude delta

delta = np.arcsin(np.dot(r_vec, K_vec)/r)

print(f"\delta = {delta} in rad, {np.degrees(delta)} in degrees")

\delta = 0.0 in rad, 0.0 in degrees


In [453]:
# Celestial longitude , lamda
temp1 = np.dot(r_vec/r, J_vec/np.cos(delta))
temp2 = np.dot(r_vec/r, I_vec/np.cos(delta))

lamda1 = np.arcsin(temp1)
lamda2 = np.arccos(temp2)

print(temp1, temp2,"\n")
print(lamda1, np.degrees(lamda1))
print(lamda2, np.degrees(lamda2))

########## select the angle suitably

# fix suitable value
Lamda = np.deg2rad(146.310)

0.5547001962252291 -0.8320502943378436 

0.5880026035475676 33.69006752597979
2.5535900500422257 146.30993247402023


In [454]:
# Elementray Rotation matrices

# Note: Theta here is in radians

def C1(theta):
  return np.matrix([
                   [ 1, 0             , 0           ],
                   [ 0, np.cos(theta) , np.sin(theta)],
                   [ 0, -np.sin(theta), np.cos(theta)]
                   ])
  
def C2(theta):
  return np.matrix([
                   [ np.cos(theta), 0,-np.sin(theta)],
                   [ 0            , 1, 0            ],
                   [ np.sin(theta), 0, np.cos(theta)]
                   ])
  
def C3(theta):
  return np.matrix([
                   [ np.cos(theta), np.sin(theta), 0 ],
                   [-np.sin(theta), np.cos(theta) , 0 ],
                   [ 0            , 0             , 1 ]
                   ])

In [455]:
C_LH = C2(-np.pi/2)*C2(np.pi/2 - delta)*C3(Lamda)
C_LH

matrix([[-0.83205095,  0.55469922,  0.        ],
        [-0.55469922, -0.83205095,  0.        ],
        [ 0.        ,  0.        ,  1.        ]])

In [456]:
v_LH = C_LH*np.reshape(v_vec,(3,1))
v_LH = np.asarray(v_LH).reshape(-1)
v_LH


array([-1.6641019 , -1.10939843,  7.5       ])

In [457]:
i_r = [1, 0, 0]
i_lamda = [0, 1, 0]
i_delta = [0, 0, 1]

In [458]:
# Flight Path angle, phi

phi = np.arcsin(np.dot(v_LH/v, i_r))

print(f"\delta = {phi} in rad, {np.degrees(phi)} in degrees")

\delta = -0.21606568155870215 in rad, -12.379651650931256 in degrees


In [459]:
# Velocity Azimuth , shi
temp1 = np.dot(v_LH/v, i_lamda/np.cos(phi))
temp2 = np.dot(v_LH/v, i_delta/np.cos(phi))

shi1 = np.arcsin(temp1)
shi2 = np.arccos(temp2)

print(temp1, temp2,"\n")
print(shi1, np.degrees(shi1))
print(shi2, np.degrees(shi2))

shi = np.deg2rad(219.105) #select value suitably

-0.14632760963699867 0.9892361854774228 

-0.14685489499446414 -8.414165684019673
0.14685489499446475 8.414165684019709


In [460]:
print(np.cos(i),"\n",np.cos(delta), np.sin(shi),"\n",np.cos(delta) * np.sin(shi))

-0.14632474903078882 
 1.0 -0.6307435278545224 
 -0.6307435278545224


In [461]:
r = 6578.14
v = np.sqrt(mew_earth/r) - 0.600

a = -mew_earth/2 /(v**2/2 - mew_earth/r)
a

5729.00852788584